### ISSUE TITLE
Courses comunications SCORM Angular

### ISSUE THREAD

**Issue by erancov** [gabrieldoty/simplify-scorm#28] opened 2020-03-16 13:26 UTC
Hi! I'm trying to create an angular application where people can upload courses(SCORM). I don't understand how to communicate with that courses, how do i get data, and store in my db. How to create the relation between courses and my application. This need s to be dynamic. Thank you!

!!!I don't want to create courses. I just want to use them.

**Comment by xob** [comment] 2020-04-13 14:06
I hear you, and understand that the project could use a bit more example code of how to use it in a "complete package". More example code will exist, eventually. In the meantime, I am closing this issue, as it is a duplicate of #16

**Closed as completed by xob** 2020-04-13 14:06 UTC
